spring:
  application:
    name: learn-nacos-discovery

  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.0.166:8848
        username: nacos
        password: nacos
        namespace: a6d0a7ad-e561-4860-babc-8a838ebf42fa
        group: LEARN_GROUP

server:
  port: 20100