
spring:
  application:
    name: learn-job
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.166:3306/learn_job?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: YYfei1108..
    hikari:
      maximum-pool-size: 10
learn:
  job:
    admin-addresses: http://127.0.0.1:10030/xxl-job-admin
    access-token: default_token
    app-name: learn-job
    ip:
    port: 40000
    log-path: /Users/yanfei/logs/learn-job/jobhandler
    log-retention-days: 30
server:
  port: 40000
